### ISSUE TITLE
add `gpu uuid` to the fingerprinted attributes

### ISSUE THREAD

**Issue by shumin1027** [hashicorp/nomad-device-nvidia#11]
I want to use `gpu uuid` when configuring `affinity` or `constraint`，but there is no such attribute in fingerprinted attributes，how should it be achieved?

[Fingerprinted Attributes](https://developer.hashicorp.com/nomad/plugins/devices/nvidia#fingerprinted-attributes)

**Comment by lgfa29** [comment]
Hi @shumin1027 👋 

I believe the UUID is just missing from the documentation as the [fingerprinter does report the UUID](https://github.com/hashicorp/nomad-device-nvidia/blob/main/nvml/client.go#L119).

Could you check if the GPU UUID is present when you run `nomad node status -verbose <node ID>`?

**Comment by shumin1027** [comment]
> Hi @shumin1027 👋
> 
> I believe the UUID is just missing from the documentation as the [fingerprinter does report the UUID](https://github.com/hashicorp/nomad-device-nvidia/blob/main/nvml/client.go#L119).
> 
> Could you check if the GPU UUID is present when you run `nomad node status -verbose <node ID>`?

@lgfa29 
Thank you，
It's not that the documentation is missing，all fingerprinted attributesare defined here：
https://github.com/hashicorp/nomad-device-nvidia/blob/541c8ca6aee84e14c4f0e79c39c1a2c431008dff/fingerprint.go#L13-L24

And here's how to populate the attribute data, it can be seen that there is indeed no `GPU UUID`
https://github.com/hashicorp/nomad-device-nvidia/blob/541c8ca6aee84e14c4f0e79c39c1a2c431008dff/fingerprint.go#L167

https://github.com/hashicorp/nomad-device-nvidia/blob/541c8ca6aee84e14c4f0e79c39c1a2c431008dff/fingerprint.go#L181

**Comment by shumin1027** [comment]
@lgfa29 
By the way，when I try to solve this problem by adding `GPU UUID` to fingerprinted attributes here:
https://github.com/hashicorp/nomad-device-nvidia/blob/541c8ca6aee84e14c4f0e79c39c1a2c431008dff/fingerprint.go#L181

But a new problem was found：
When a device like the `NVIDIA Tesla K80` with a `Dual GPU`，there will be a conflict :
https://github.com/hashicorp/nomad-device-nvidia/blob/541c8ca6aee84e14c4f0e79c39c1a2c431008dff/fingerprint.go#L164-L167

Two GPUs with different UUIDs will be treated as one device with the same fingerprinted attributes

I still don't know how to solve this problem elegantly

**Comment by lgfa29** [comment]
Oh, you're right @shumin1027, I misunderstood the code. I don't think it's possible to fix this at the plugin level, it seems like a limitation within Nomad.

I opened https://github.com/hashicorp/nomad/pull/15455 to try and fix this. I'm building custom binaries for you to test if you have the chance and I will post them here once they're ready.

**Comment by lgfa29** [comment]
Here are the custom binaries:  https://github.com/hashicorp/nomad/actions/runs/3604896100#artifacts

**Comment by shumin1027** [comment]
@lgfa29  It's great, I will continue to test

**Comment by lgfa29** [comment]
Hi @ruspaul013 👋 

I answered in your post, but TL;DR: yes, you need to upgrade your Nomad clients to a version that includes this change.

**Comment by ruspaul013** [comment]
Hello @lgfa29 👋
Thank you so much for the answer. I posted an update on the forum.
